import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-mainText-100 
                        text-white 
                        container 
                        m-auto 
                        font-mainFont 
                        box-border
                        flex flex-col
                        items-center
                        ">
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  )
}
